### ISSUE TITLE
🐞 Bug: Issue with bind mounts

### ISSUE THREAD

**Issue by Diagonet** [ofkm/arcane#475]
### Bug Description

Not a docker expert here but Im having this issue when I mount a volume using a relative address, for example my docker compose has
```
services:
  app:
    volumes:
      - ./data:/data
```
My projects folder is at /home/ubuntu/docker/stacks so I would expect it to bind /home/ubuntu/docker/stacks/app/data but Arcane instead binds /app/data/projects/app/data . I understand the container cannot see the path outside of it, I think dockge gets around it by having the path to my folder match the path inside the container so it can tell where it is? To be honest I have no idea. Running docker compose up -d inside the folder works normally, so does arcane's restart. Deploying from arcane causes errors.

### Steps To Reproduce

Just use a relative bind mount in any docker image that needs a config file inside of it, it errors because it can't find the file.

### Expected Behavior

Expected to bind the volume relative to the docker compose file location.

### Actual Behavior

It binds relative to /app/data/projects/ instead.

### Arcane Version

v1.1.0

### Operating System

macOS

### Browser

Vivaldi

### Docker Version

28.4.0

**Comment by kmendell** [comment]
Ill look into this, Thanks!

**Comment by cabaucom376** [comment]
@kmendell I would also like to report that I have been trying to figure out why I cannot get this traefik compose to bind mount its relative config file when deploying a compose project:
```yaml
# compose.yaml

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/traefik.yaml:ro # this is not mounting upon deploying the compose project
      - ./data/certs/:/var/traefik/certs/:rw
    restart: unless-stopped
```
```yaml
# ./config/traefik.yaml

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# (Optional) Change log level and format
# - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
log:
 level: DEBUG

# (Optional) Enable API and Dashboard, don't do in production
# api:
#   dashboard: true
#   insecure: true

# Change EntryPoints
entryPoints:
  # (Optional) Enables http
  web:
    address: :80
    # (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  # HTTPS
  websecure:
    address: :443

# ...
```

The only way I managed to deploy and bind mount my Traefik project is by manually entering my projects/traefik directory and executing `docker compose up -d`. This ensures that everything mounts perfectly. However, I have to repeat this manual process every time the compose project is stopped. For instance, if I use the `Down` button on the project and then `Deploy` it, it fails to mount, and I have to manually run `docker compose up` in the project directory to get it working again.

**Comment by kmendell** [comment]
Can you try this image: `ghcr.io/ofkm/arcane:env-test`? This should be fixed now along Side the loading of env

**Comment by cabaucom376** [comment]
Does not seem to have resolved my particular case, I still have to manually start the compose project via `docker compose up -d`. When starting from the Arcane UI it still doesn't mount the relative file/directory properly. I have since updated my compose to use just a relative path instead of a file directly (so Traefik can watch for new yaml files during runtime) and the issue still persists.
```yaml
# compose.yaml

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik:ro # something is still going on here that doesnt occur with manual `docker compose up -d`
      - ./data/certs/:/var/traefik/certs/:rw # this may also be affected but cannot tell as traefik never runs to the point of generating certs
    restart: unless-stopped
```
```yaml
# ./config/traefik.yaml

# ...

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik
    watch: true
```

**Comment by kmendell** [comment]
@cabaucom376 interesting, I was able to get it to work it created the data directory for me, however this isn't inside a docker container just locally on my MacBook so that may have something to do with it ... 

<img width="957" height="764" alt="Image" src="https://github.com/user-attachments/assets/cfa0e1c6-e854-41d0-af74-5d9e2a78a921" />

**Comment by Diagonet** [comment]
> ghcr.io/ofkm/arcane:env-test

This image doesn't seem to have fixed it, at least for me, it created the data folder at /app/data/projects/appname/data

**Comment by cabaucom376** [comment]
Just tried with a new compose/env combo and can confirm its not handling bind mounts when deploying.
```yaml
# compose.yaml

services:
  server:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:${FORGEJO_TAG:-12}
    volumes:
      - ./forgejo:/data # not mounted/created on deploy
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - private
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=${DATABASE_NAME:-forgejo}
      - FORGEJO__database__USER=${DATABASE_USER:-forgejo}
      - FORGEJO__database__PASSWD=${DATABASE_PASS:?please provide a db password}
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:${POSTGRES_TAG:-14}
    volumes:
      - ./postgres:/var/lib/postgresql/data # not mounted/created on deploy
    networks:
      - private
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-forgejo}
      - POSTGRES_USER=${DATABASE_USER:-forgejo}
      - POSTGRES_PASSWORD=${DATABASE_PASS:?please provide a db password}
    restart: unless-stopped

networks:
  public:
    external: true
  private:
    external: false
```
```env
# .env

# Global Configuration
DATABASE_NAME="forgejo"
DATABASE_USER="forgejo"
DATABASE_PASS="forgejo"

# Server Configuration
FORGEJO_TAG="12"

# Database Configuration
POSTGRES_TAG="14"
```

**Comment by kmendell** [comment]
> > ghcr.io/ofkm/arcane:env-test
> 
> This image doesn't seem to have fixed it, at least for me, it created the data folder at /app/data/projects/appname/data

Where are you expecting it to be placed? 

If you run docker compose up -d inside that directory normally it would place it in the location of the compose file which is what that logic does, I may be confused on what you are asking here

**Comment by Diagonet** [comment]
> > > ghcr.io/ofkm/arcane:env-test
> > 
> > 
> > This image doesn't seem to have fixed it, at least for me, it created the data folder at /app/data/projects/appname/data
> 
> Where are you expecting it to be placed?
> 
> If you run docker compose up -d inside that directory normally it would place it in the location of the compose file which is what that logic does, I may be confused on what you are asking here

My docker compose file is at /home/ubuntu/docker/stacks/appname so when I use docker compose up at that folder it creates a data folder /home/ubuntu/docker/stacks/appname/data , currently arcane creates the data folder at /app/data/projects/appname/data when I use deploy. 

It seems to bind mount relative to the /app/data/projects inside of the container, instead of the folder in the local machine. I believe similar projects like dockge ask the user to match both sides of the volume config to get around this limitation. For example:
```
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      # - /host/path/to/projects:/app/data/projects instead of this
      -/home/ubuntu/docker/stacks:/home/ubuntu/docker/stacks #in my case
    environment:
      - APP_URL=http://localhost:3552
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=xxxxxxxxxxxxxxxxxxxxxx
      - JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxx
    restart: unless-stopped

```
But then it would need to be configured to search for the compose file I think?

**Comment by kmendell** [comment]
oh yeah okay sorry it worked for me as im not in a docker environment, I think I know a way around this but ill have to test it for sure. Ill keep you in the loop

**Comment by Diagonet** [comment]
Nothing to be sorry for! I'm still a docker newbie so I probably didn't explain it well tbh.

**Comment by Clementinox** [comment]
On the previous arcane version before 1.0
this section`- /host/path/to/projects:/app/data/projects` 
used to be like this`- /host/path/to/projects:/host/path/to/projects`
Both sides of the colon had the same path on the host for the projects/stack folder. Could this be the issue?

**Comment by kmendell** [comment]
Yes you could mount it to that and then change the path that arcane uses inside the container in the settings that would work as well.

**Comment by Diagonet** [comment]
Easiest way would be adding an env variable we can use to set Arcane's stacks path, ideal way would be Arcane being able to search where the compose files are and using that as the path

**Comment by Clementinox** [comment]
> Yes you could mount it to that and then change the path that arcane uses inside the container in the settings that would work as well.

I tried it and I get this when i try to pull immich for example.

this is the part in immich 
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

It seems it's not detecting that I have variables in my env file which I can see in arcane env section.

<img width="674" height="362" alt="Image" src="https://github.com/user-attachments/assets/33f5ace5-50e8-48d0-9868-6d4bf94fe315" />

Other thing I noticed. I see a bunch of these popup in arcane but these variables are set in the containers it's referring to:
```
level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"POSTGRES_DB\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"DB_PASSWORD\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"DB_USERNAME\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"DB_DATABASE_NAME\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"DB_DATA_LOCATION\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
level=warning msg="The \"POSTGRES_DB\" variable is not set. Defaulting to a blank string."
```

**Comment by cabaucom376** [comment]
@Clementinox try it with the `env-test` image tag for Arcane.

**Comment by Clementinox** [comment]
@cabaucom376 That worked thanks man!

So everyone has an idea what I did. Docker compose for arcane using env-test:
```
services:
  arcane:
    container_name: arcane
    environment:
      - APP_URL=https://arcane.domain.com
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=XXX
      - JWT_SECRET=XXX
    image: ghcr.io/ofkm/arcane:env-test
    ports:
      - '3552:3552'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /path/stacks/arcane/data:/app/data
      - /path/stacks:/path/stacks/
```

In arcane GUI, make sure the "Projects Directory" is set the same as your stack path, in my scenario it's: /path/stacks

**Comment by cabaucom376** [comment]
I can also confirm having the two paths the same fixes my bind mount problems.

1. In Arcane, set `Settings > General Settings > Projects Directory` to the path on your host machine. In my case it was `/home/docker`
2. `docker compose down` Arcane
3. Edit Arcane's compose.yaml to adjust the container mount location of projects
```yaml
services:
  arcane:
    container_name: arcane
    image: ghcr.io/ofkm/arcane:${IMAGE_TAG:-latest}
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Make sure your host projects directory is the same as Arcane's container projects directory
      # i.e. for me `/home/docker:/app/data/projects` -> `/home/docker:/home/docker`
      - /home/docker:/home/docker
    environment:
      - APP_URL=${APP_URL:-http://localhost:3552}
      - PUID=1000
      - PGID=1000
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:?}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
```
4. Save changes and run `docker compose up -d`

**Comment by kmendell** [comment]
Okay cool good to know that works... however im still going to try and find a solution to this, as i know it is possible... just may take alot of digging

**Comment by kmendell** [comment]
For now what i will do is update the documentation to say to mount into the same path and then in the onboarding to update the path used for porjects there. I put this on my todolist to investigate further but since there is a solutuion i will close this out once i update the docs.

**Comment by Diagonet** [comment]
> For now what i will do is update the documentation to say to mount into the same path and then in the onboarding to update the path used for porjects there. I put this on my todolist to investigate further but since there is a solutuion i will close this out once i update the docs.

Can you also add an env variable so we can set the project path config from the compose too please?

**Comment by cabaucom376** [comment]
Also, just throwing out an idea, but if you decide to add an environment variable, I find it annoying as a user that there are potentially two places to set things. So, whenever the environment variable is set, it would be great if you could disable the setting in the UI and just have it as a non-interactive display.

**Comment by kmendell** [comment]
I can add one yes, It would most likely set it up so all the UI values can be used via Environment variables, and would disabled (similar to the other project I maintain pocket-id)

**Comment by kmendell** [comment]
You should be able to set the PROJECTS_DIRECTORY variable now, if UI_CONFIGURATION_DISABLED is also set to true.
