### ISSUE TITLE
🐞 Bug: Dashboard showing wrong info for agent.

### ISSUE THREAD

**Issue by vladaurosh** [ofkm/arcane#479]
### Bug Description

My "master" is running on arm64 host, agent is armv7.
When I switch to an agent in UI, dashboard is showing wrong info for number of containers and docker engine arch.
Number of containers is 16 of 8 running!? My master has 16 running container so probably some mix up has happened.
Also architecture shown for agent is aarch64, should be arm(v7).

### Steps To Reproduce

1. connect armv7 agent to arm64 master

### Expected Behavior

Correct number of running containers (8 in my case) 
Correct architecture of an agent docker.

### Actual Behavior

Wrong number of containers on agent. Wrong docker agent architecture.

### Screenshots

![Image](https://github.com/user-attachments/assets/95bc4a8f-a2d5-4766-8dd3-cecbb1a6b364)

### Arcane Version

v1.1.0

### Operating System

Linux

### Browser

Chrome

### Docker Version

28.3.3

**Comment by kmendell** [comment]
@vladaurosh Can you try the `ghcr.io/ofkm/arcane:next` image? I moved stuff over to use websockets, and i think i fixed this as well.

**Comment by vladaurosh** [comment]
Hey @kmendell 
I've tried with "next" image, for master, but still seeing the same. But I think the problem is that I'm running agent with "latest" image, it's armv7. 
In agent I see these errors:
INF HTTP error: 404 not found request.time=2025-09-17T00:23:34.845Z request.method=GET request.host=x.x.x.x:3553 request.path=/api/environments/0/stats/ws request.query="" request.params=map[id:0] request.route="" request.ip=x.x.x.x request.referer="" request.length=0 response.time=2025-09-17T00:23:34.845Z response.latency=22.458µs response.status=404 response.length=0

Since you've mentioned websockets, I am guessing I'd need agent running with the fixed version as these errors (404) are for /ws endpoints.

**Comment by kmendell** [comment]
This should be fixed here: https://github.com/ofkm/arcane/commit/3a7b858a89dee7948326542796afdcbfa993bf9b, the `next` image should be available again soon if you would like to test it.

**Comment by kmendell** [comment]
Yes both of them would need to be the same version for it to work.

**Comment by vladaurosh** [comment]
Unfortunately, this is still present after updating to 1.2.0. 
While number of running containers on agent is correct (8), not sure where it picked 16 from. 
Also architecture of docker agent is wrong, showing "linux • aarch64", while it's running on arm v7.

**Comment by vladaurosh** [comment]
Can this be reopened @kmendell ?

**Comment by kmendell** [comment]
i know what the issue is ill get it fixed.
