### ISSUE TITLE
🐞 Bug: High Memory Usage

### ISSUE THREAD

**Issue by nholben** [ofkm/arcane#503]
### Bug Description

After running the container for less than 24 hours, memory usage grows to over 20gb. Has happened twice after stopping and recreating the container.

### Steps To Reproduce

Run container, wait.

### Expected Behavior

Stable, reasonably allocated memory usage.

### Actual Behavior

Memory runaway.

### Screenshots

<img width="1411" height="767" alt="Image" src="https://github.com/user-attachments/assets/0e1b750e-8f26-4b32-9ad5-dceeaae22a71" />

### Arcane Version

v1.1.0

### Operating System

Linux

### Browser

Firefox

### Docker Version

28.4

### Additional Context

Host system: Debian 13

I'm a hobbyist self-hoster so I don't know much about how to dig into this problem. But nothing jumps out in the container logs as being wrong.

**Comment by sugarfunk** [comment]
I am seeing this as well. Arcane using 85%+ of memory.

**Comment by kmendell** [comment]
Hmm.... Ill look into this.. Sorry about the trouble.

**Comment by vladaurosh** [comment]
Interesting, I'm running arm64 version of arcane, and mem usage is stable at just 10MB in last 24 hours.

**Comment by weedy** [comment]
Set limits. 
```
services:
  arcane:
    container_name: arcane
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 192M
```
But I've never seen Arcane move more then +/- 8-12mb from container startup.
Like my usage graph is a almost flat line from container boot.

**Comment by dhanadhan** [comment]
Look at the container logs, you might see something every 5-10 sec. See if it shows you something like missing variables or variables not set errors. If you see these errors consistently, CPU and RAM usage will keep going up. I then changed PUID and GUID to local user id and logs stopped and so the CPU and RAM usage. The issue might be permission related. 

I get this error even though I set PUID and PGID to 1000 in compose.
```
level=warning msg="The \"UID\" variable is not set. Defaulting to a blank string.
level=warning msg="The \"GID\" variable is not set. Defaulting to a blank string.
```

**Comment by sugarfunk** [comment]
@weedy understand, but capping doesn't resolve a potential issue. @dhanadhan I am getting constant error for missing db password variable. Still not sure that would impact memory, but can see CPU.

The DB password variable shows that variable is only for external PG, no mention of that for internal on https://arcane.ofkm.dev/docs/configuration/environment

```
time=2025-09-17T13:20:29Z level=warning msg=The \"DB_PASSWORD\" variable is not set. Defaulting to a blank string.
time=2025-09-17T13:20:29Z level=warning msg=The \"DB_PASSWORD\" variable is not set. Defaulting to a blank string.
```

<img width="761" height="696" alt="Image" src="https://github.com/user-attachments/assets/52ab91ba-2630-42e6-8911-b54a971e5957" />

**Comment by nholben** [comment]
I'm not seeing any DB password errors in my container logs. The only messages I see are: WRN slow sql query


``Sep 17 13:07:28.648 WRN slow sql query [1.252171938s >= 200ms] slow_query=true query="UPDATE `image_updates` SET `repository`=\"postgres\",`tag`=\"15\",`has_update`=true,`update_type`=\"tag\",`current_version`=\"15\",`latest_version`=\"17\",`current_digest`=NULL,`latest_digest`=NULL,`check_time`=\"2025-09-17 13:07:27.387\",`response_time_ms`=232,`last_error`=NULL,`auth_method`=\"anonymous\",`auth_username`=NULL,`auth_registry`=\"docker.io\",`used_credential`=false,`created_at`=\"0000-00-00 00:00:00\",`updated_at`=\"2025-09-17 13:07:28.637\" WHERE `id` = \"sha256:b3d48187cc8a71167b6c8bb2b30230bf3badbaf0010a4426ca8e07af3eae038e\"" duration=1.252171938s rows=1 file=github.com/ofkm/arcane-backend/internal/services/image_update_service.go:830``

**Comment by kmendell** [comment]
Can you try the `ghcr.io/ofkm/arcane:next` image and see if this still happens? if you using a remote env you will have to update that to the `ghcr.io/ofkm/arcane-headless:next` image as well

**Comment by nholben** [comment]
> Can you try the `ghcr.io/ofkm/arcane:next` image and see if this still happens? if you using a remote env you will have to update that to the `ghcr.io/ofkm/arcane-headless:next` image as well

Thanks for the quick response! I've been running for about an hour now and am continuing to watch the memory usage grow, it's up to about 1gb now. It also looks like the landing page's metrics are no longer loading.


<img width="1340" height="465" alt="Image" src="https://github.com/user-attachments/assets/d7268e5e-77e6-49af-b9e2-a6634bde6e98" />

**Comment by user00265** [comment]
@nholben, how is the rest of this host doing? What are the specs for it? What architecture is the processor? How many containers are you running?

Something is not quite right here. My instance runs for ungodly long periods of time and I test unreleased stuff for @kmendell all the time and I have never seen the containers act up.

**Comment by kmendell** [comment]
As far as the ENV varibles missing, That is because some of your ocmpose files are using ENV interpalation you should see that fixed in the next images as well. -- The dashboard metrics is interesting, Are you on a "Remote Environment" thats not using the `next` image?

**Comment by sugarfunk** [comment]
@kmendell next tag fixed the db_password. Monitoring for CPU/Ram. Looks good so far, but will report back.

This is pinging the logs about every 7 seconds. I am gussing this is expected.

```
Sep 18 19:38:35.154 INF Filesystem change detected, syncing projects
Sep 18 19:38:35.161 INF Project sync completed after filesystem change
Sep 18 19:38:46.204 INF Filesystem change detected, syncing projects
Sep 18 19:38:46.211 INF Project sync completed after filesystem change
Sep 18 19:38:51.500 INF Filesystem change detected, syncing projects
Sep 18 19:38:51.507 INF Project sync completed after filesystem change
Sep 18 19:38:55.008 INF Filesystem change detected, syncing projects
Sep 18 19:38:55.014 INF Project sync completed after filesystem change
Sep 18 19:38:58.856 INF Filesystem change detected, syncing projects
Sep 18 19:38:58.863 INF Project sync completed after filesystem change
Sep 18 19:39:07.114 INF Filesystem change detected, syncing projects
Sep 18 19:39:07.121 INF Project sync completed after filesystem change
Sep 18 19:39:15.008 INF Filesystem change detected, syncing projects
Sep 18 19:39:15.014 INF Project sync completed after filesystem change
Sep 18 19:39:21.584 INF Filesystem change detected, syncing projects
Sep 18 19:39:21.591 INF Project sync completed after filesystem change
Sep 18 19:39:25.011 INF Filesystem change detected, syncing projects
Sep 18 19:39:25.017 INF Project sync completed after filesystem change
Sep 18 19:39:29.361 INF Filesystem change detected, syncing projects
Sep 18 19:39:29.368 INF Project sync completed after filesystem change
```

**Comment by user00265** [comment]
I was talking to @kmendell about it and his environment is working right. Mine does as well, but here's the catch -- the watcher routine just sits there and waits for file changes. Something is writing to those files it is looking for. You can set the `LOG_LEVEL` environment to `debug` for a bit to see the database queries and then you should be able to see what is being modified.

**Comment by sugarfunk** [comment]
@user00265 I must have this conceptualized wrong or not configured as intended. My Stacks folder includes my bind data files, so as my other containers are doing their thing, their are writing to the db files and other things. This is what is causing the constant churn. 

```
Sep 18 20:21:00.373 DBG Filesystem change detected path=data/projects/sonarr/data/sonarr.db-wal operation=WRITE
Sep 18 20:21:00.373 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-shm operation=WRITE
Sep 18 20:21:00.373 DBG Filesystem change detected path=data/projects/sonarr/data/sonarr.db-wal operation=WRITE
Sep 18 20:21:00.373 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-shm operation=WRITE
Sep 18 20:21:00.376 DBG Filesystem change detected path=data/projects/sonarr/data/sonarr.db-wal operation=WRITE
Sep 18 20:21:00.377 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.379 DBG Filesystem change detected path=data/projects/sonarr/data/sonarr.db-wal operation=WRITE
Sep 18 20:21:00.380 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.380 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.383 DBG Filesystem change detected path=data/projects/sonarr/data/sonarr.db-wal operation=WRITE
Sep 18 20:21:00.386 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.389 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.393 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.422 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.422 DBG Filesystem change detected path=data/projects/radarr/data/radarr.db-wal operation=WRITE
Sep 18 20:21:00.439 DBG Filesystem change detected path=data/projects/sonarr/data/sonarr.db-wal operation=WRITE
Sep 18 20:21:03.439 INF Filesystem change detected, syncing projects
Sep 18 20:21:03.440 DBG SQL query executed [622.392µs] query="SELECT * FROM `settings` WHERE key = \"projectsDirectory\" ORDER BY `settings`.`key` LIMIT 1" duration=622.392µs rows=1 file=github.com/ofkm/arcane-backend/internal/services/settings_service.go:374
Sep 18 20:21:03.441 DBG SQL query executed [653.883µs] query="SELECT * FROM `projects` WHERE path = \"data/projects/agregarr\" OR dir_name = \"agregarr\" ORDER BY `projects`.`id` LIMIT 1" duration=653.883µs rows=1 file=github.com/ofkm/arcane-backend/internal/services/project_service.go:257
Sep 18 20:21:03.442 DBG SQL query executed [678.303µs] query="SELECT * FROM `projects` WHERE path = \"data/projects/arcane\" OR dir_name = \"arcane\" ORDER BY `projects`.`id` LIMIT 1" duration=678.303µs rows=1 file=github.com/ofkm/arcane-backend/internal/services/project_service.go:257
Sep 18 20:21:03.443 DBG SQL query executed [512.581µs] query="SELECT * FROM `projects` WHERE path = \"data/projects/audiobookshelf\" OR dir_name = \"audiobookshelf\" ORDER BY `projects`.`id` LIMIT 1" duration=512.581µs rows=1 file=github.com/ofkm/arcane-backend/internal/services/project_service.go:257
Sep 18 20:21:03.443 DBG SQL query executed [375.308µs] query="SELECT * FROM `projects` WHERE path = \"data/projects/beszel-workhorse\" OR dir_name = \"beszel-workhorse\" ORDER BY `projects`.`id` LIMIT 1" duration=375.308µs rows=1 file=github.com/ofkm/arcane-backend/internal/services/project_service.go:257
```

**Comment by user00265** [comment]
It really shouldn't be caring about those files, but I reckon the original intention of projects is only for the source files themselves -- compose and env files, but it seems the filtering out is not in place.

So, there is a bug, and yeah, the way you're using the projects folder is not how the design was conceived. Once the filtering is fixed it SHOULDN'T be an issue, BUT I recommend not using it like that as it still triggers the events and the code still has to check whether it should ignore it or not.

**Comment by user00265** [comment]
@sugarfunk, are you using the bind mounts in the project folders as well?

**Comment by sugarfunk** [comment]
@user00265 yup. Always deployed like that. I tried to illustrate below. I do that for my backup strategy. I turn down all containers and can backup the ../docker folder.

../docker
->/App1
-->compose.yaml
-->/data
->/App2
->/App3

etc

**Comment by nholben** [comment]
@user00265 I'm using a similar folder hierarchy as sugarfunk with bind mounts nested in the project folders. And my debug logs are showing lots of filesystem change watches as well. Maybe this is the source of the issue....I'll recreate the container with no mounts and see what happens. To answer your other questions the rest of my system is fine. It's running amd64 arch, 64gb of ram, 70ish containers. @kmendell I'm not running the remote environment.

**Comment by dhanadhan** [comment]
Tried the "next" image, CPU usage is fine, not quite complete 0 at idle like how it was before I think. Still seeing the same error
```
Sep 18 19:39:29.361 INF Filesystem change detected, syncing projects
Sep 18 19:39:29.368 INF Project sync completed after filesystem change
```

**Comment by kmendell** [comment]
Welp i guess my goroutine logic needs a bit of work huh? ;) ill fix this now

**Comment by kmendell** [comment]
This should be fixed here: https://github.com/ofkm/arcane/commit/c957681dc46e43e7f963d22a4721499056def220. The `next` image should be available shortly if you want to test it.

**Comment by weedy** [comment]
> [@user00265](https://github.com/user00265) 
> 
> ../docker
> ->/App1
> -->compose.yaml
> -->/data
> ->/App2
> ->/App3

So the way I've seen it done and what I ended with on my NAS.
I don't think you want to have the fswatcher firing off for every unrelated inode change

```
/mnt/docker
--> /appdata
----> /arcane
------> (app config, database, cache, whatever)
----> /App2
--> /compose(my local template directory)
----> /base_settings
------> compose.yaml (fake app that has my basic settings and a empty .env because the nginx example from arcane is useless for me)
--> /other_shit
--> /projects
----> /arcane
------> compose.yaml
----> /App2
------> compose.yaml
```

**Comment by user00265** [comment]
I was brainstorming with @kmendell earlier and we refactored the watcher. Now it is working the way it should and will only react to compose and env files. The `next` image has the commit: https://github.com/ofkm/arcane/commit/ae159f9d38faf191f9f64cc6db31455162fb4947

**Comment by kmendell** [comment]
The watcher now only wtahces for folders/compose files and .envs files , all this does is sync the data to the database as db reads are faster than reading from the disk .

**Comment by dhanadhan** [comment]
Just updated the "next" image and I can't edit any compose file anymore. Getting error: `Failed to Save Project: project not found`

Container logs:
`
Sep 19 05:27:58.248 INF HTTP error: 400 bad request request.time=2025-09-19T05:27:58.248Z request.method=PUT request.host=192.168.20.150:3552 request.path=/api/environments/0/projects/beszel request.query="" request.params="map[id:0 projectId:beszel]" request.route=/api/environments/:id/projects/:projectId request.ip=192.168.x.x request.referer=http://192.168.x.x:3552/projects/f060ebd8-a298-49aa-xxxxxxxxxxx request.length=771 response.time=2025-09-19T05:27:58.248Z response.latency=802.612µs response.status=400 response.length=45
`

**Comment by kmendell** [comment]
Well interesting... Ill take a look into that and will let you know.

**Comment by kmendell** [comment]
That part should be fixed here: https://github.com/ofkm/arcane/commit/1cb7ab2f93a86f281903e3b72726e6c5e9be4794. The `next` image should be available again in a few minutes.

**Comment by dhanadhan** [comment]
> That part should be fixed here: [1cb7ab2](https://github.com/ofkm/arcane/commit/1cb7ab2f93a86f281903e3b72726e6c5e9be4794). The `next` image should be available again in a few minutes.

Just updated the `next` image, and no change. I still can't edit any compose. Arcane also freezes when go inside some projects. No idea why, then when I load the home page, it's fine. 

``
Sep 19 21:54:43.829 INF HTTP error: 400 bad request request.time=2025-09-19T21:54:43.828Z request.method=PUT request.host=192.168.x.x:3552 request.path=/api/environments/0/projects/beszel request.query="" request.params="map[id:0 projectId:beszel]" request.route=/api/environments/:id/projects/:projectId request.ip=192.168.x.x request.referer=http://192.168.x.x:3552/projects/f060ebd8-a298-49aa-b72c-xxxxxx request.length=771 response.time=2025-09-19T21:54:43.829Z response.latency=612.586µs response.status=400 response.length=45
``

**Comment by kmendell** [comment]
Are you sure it pulled the latest image? Its still sending the project name instead of the ID. Ill try againa fter i finish what im working on.

**Comment by dhanadhan** [comment]
> Are you sure it pulled the latest image? Its still sending the project name instead of the ID. Ill try againa fter i finish what im working on.

Yes, I deleted the old image first and then repulled. And just did that again, same issue.

**Comment by kmendell** [comment]
Okay ill take a look again, i couldnt reproduce it before but ill check.

**Comment by sugarfunk** [comment]
Have had time to test this for a few days. The CPU is normalized now. No errors spams in the logs. Memory usage still exploding. Red bar on top is Arcane.

<img width="1372" height="1340" alt="Image" src="https://github.com/user-attachments/assets/ef148980-c51b-4709-8f3f-35d9b6623815" />

**Comment by kmendell** [comment]
what did you do at that time? is it when viewing logs of a container? just trying to pinpoint the issue

**Comment by kmendell** [comment]
> > Are you sure it pulled the latest image? Its still sending the project name instead of the ID. Ill try again after i finish what im working on.
> 
> Yes, I deleted the old image first and then repulled. And just did that again, same issue.

I cant repliate this, im wondering if maybe the ID of the porjetc got set to the name somehow, Can you check in the database under the projects table to see what the ID of the project is? or in the network panel of your browser tool, reload the page while on the project page , and you should see the ID based on the URL you are accessing it seems like its has a correct ID though. Im wondering if it could also be a browser cache thing.

**Comment by dhanadhan** [comment]
> > > Are you sure it pulled the latest image? Its still sending the project name instead of the ID. Ill try again after i finish what im working on.
> > 
> > 
> > Yes, I deleted the old image first and then repulled. And just did that again, same issue.
> 
> I cant repliate this, im wondering if maybe the ID of the porjetc got set to the name somehow, Can you check in the database under the projects table to see what the ID of the project is? or in the network panel of your browser tool, reload the page while on the project page , and you should see the ID based on the URL you are accessing it seems like its has a correct ID though. Im wondering if it could also be a browser cache thing.

Thanks for checking. 

I pulled v1.2 today and those issues are gone. It might be cached issue as I have seen it behaving strange when browsing directly vs incognito mode. 

With v1.2 though, CPU usage have gone down, but not quite to 0% when idling.

**Comment by kmendell** [comment]
It will never be 0 depends on alot of factors. Is it to a point where you think its safe to say this is resolved?

**Comment by dhanadhan** [comment]
> It will never be 0 depends on alot of factors. Is it to a point where you think its safe to say this is resolved?

For me, yes. CPU ~0.10% and memory ~50 MB while 38 contaners running.
