### ISSUE TITLE
🐞 Bug: Project Status Unknown

### ISSUE THREAD

**Issue by keonramses** [ofkm/arcane#741]
### Bug Description

Arcane does not properly display the status of a project. It seems the env file is not being parsed.

### Steps To Reproduce

1. Deploy a project with a .env file
2. Go to projects in Arcane

### Expected Behavior

Project status should be displayed as running or stopped.

### Actual Behavior

Project status is shown as unknown

### Screenshots

<img width="1021" height="402" alt="Image" src="https://github.com/user-attachments/assets/6d6f89eb-f752-494e-b708-fa4be1e71cdd" /><br>

<img width="1919" height="256" alt="Image" src="https://github.com/user-attachments/assets/cfa54f22-60c0-434f-91a5-29b532fd4fe2" />

### Arcane Version

1.6.0

### Operating System

Linux

### Browser

Chrome 141

### Docker Version

28.4.0

**Comment by kmendell** [comment]
Did this work in 1.5.0? Loading the projects i mean?

**Comment by keonramses** [comment]
I believe it did work on v1.5.0. Unfortunately, I am unable to roll back to verify this. But I can confirm it did not work on v1.5.2.

**Comment by kmendell** [comment]
Oh thats what i meant 1.5.2, i think i know the issue but i cant reproduce it, its interpolating the varibales fine for me, at least on project created in arcanme. Where is that DOCKERDIR env set?

**Comment by kmendell** [comment]
Also "unknown" doesnt nessciarily means its not running more of a fallback , but still an issue non-theless

**Comment by keonramses** [comment]
The env file is in the same folder as the compose file for each project. Also, I notice a big delay when the project page is loaded.

<img width="684" height="456" alt="Image" src="https://github.com/user-attachments/assets/078ec51c-b29a-41ce-a581-4ef5f55d3afc" /><br>

<img width="1703" height="657" alt="Image" src="https://github.com/user-attachments/assets/716adda4-5ff6-4886-b23b-0cbf21dd5ec9" /><br>

<img width="1905" height="641" alt="Image" src="https://github.com/user-attachments/assets/52dcaacb-9c4a-4ecb-882d-b6f7334e09c6" />

**Comment by kmendell** [comment]
Set LOG_LEVEL=debug and the restart arcane and then see / attach the logs when you try to load that page

**Comment by keonramses** [comment]
Sorry for the delay. Please see the log attached.

[arcane-2025-10-20T04-12-29.log](https://github.com/user-attachments/files/22995208/arcane-2025-10-20T04-12-29.log)

**Comment by kmendell** [comment]
the DOCKER_DIR is set in the .env file ? correct?

**Comment by keonramses** [comment]
Yes it is correct. Here's a screenshot of a project that is also pointing to the same path but is defined within the yaml and not an env variable.

path proof:

<img width="1188" height="408" alt="Image" src="https://github.com/user-attachments/assets/511fd386-7247-4792-b08c-b563afb9e5d2" /><br>

env var not defined:

<img width="2170" height="967" alt="Image" src="https://github.com/user-attachments/assets/359c8290-d878-463b-ba3d-36d4fa1e7e48" /><br>

env var defined:

<img width="2172" height="1117" alt="Image" src="https://github.com/user-attachments/assets/38252afc-9d46-420a-8d3b-41df31a52abb" /><br>

**Comment by kmendell** [comment]
@keonramses Try this image i think i fixed it : `ghcr.io/ofkm/arcane:env-parsing` at least it did indeed work for me when i just tested it hoping its the same for you....

**Comment by keonramses** [comment]
Issue still persists. I am not sure if it will help but I will try to start fresh and let you know how it goes.

**Comment by kmendell** [comment]
I think the issue is when it tries to load them when not deployed from arcane actually, if you try to deploy one from the UI does the same thing happen?

**Comment by keonramses** [comment]
It does not work either. its say the var is not defined. 

<img width="425" height="184" alt="Image" src="https://github.com/user-attachments/assets/959cb67e-3e0f-43c6-bb2e-b4b9fdbe4713" />

**Comment by keonramses** [comment]
It seems it is expecting a volume and is not acknowledging the bind mount.

**Comment by kmendell** [comment]
I just pushed a new image with that same tag, that should fix it for external ones as well, and well that interesting the prasing happens directly with the compose-go sdk nothing custom happening there at least. This works for me 

<img width="1853" height="562" alt="Image" src="https://github.com/user-attachments/assets/1110e4bd-fcca-498a-bddf-4f718f5c696b" />

**Comment by keonramses** [comment]
The new build works. Although there is still a loading delay when navigating within the project section.

**Comment by kmendell** [comment]
i cant reproduce the delay, is it only the first time? or every time you load the page?

**Comment by keonramses** [comment]
It happens every time the project page is loaded. You can see it in the video below. The only time there is no delay is when clicking  into a project (reloading within the project itself is normal).

https://github.com/user-attachments/assets/5d414cae-9b00-428d-bb89-03383d034dae

**Comment by kmendell** [comment]
Hmm interesting, Ill look into it, it shouldnt be doing that. Ill look into it sometime today.

**Comment by kmendell** [comment]
@keonramses Try this image again `ghcr.io/ofkm/arcane:env-parsing` i switched the service loading to be concurrent vs blocking as it was before.

**Comment by keonramses** [comment]
Sorry for the late response. <del>The delay is still happening in this build. I even started from scratch just incase the delay was somehow being triggered by the DB. Also noticed a new bug in the projects page. The project run/stopped count does not display properly until the refresh button is used.</del>

https://github.com/user-attachments/assets/0df2032e-99f8-4f28-ab22-cacd30cc54de

**Comment by keonramses** [comment]
@kmendell Please disregard the last report, and my apologies for the wild goose chase. The delay and new count issue was being triggered by the resource limits I had on Arcane. It works well after the resource limits are removed. Can you please advise on the recommended system requirements for Arcane? 

I put limits on all my containers to avoid resource runoffs. This is the same limit I used on Portainer, so I did not think about it much when I set this up.

<img width="626" height="323" alt="Image" src="https://github.com/user-attachments/assets/aee7249b-2cb8-4a84-86f6-52dfe28262ff" /><br>

https://github.com/user-attachments/assets/2db0d578-1285-48b9-ad24-66421c03026a

**Comment by kmendell** [comment]
@keonramses I would have to do testing with it Arcane does run pretty light, but it depends on the system, if you want to do some tetsing and see if you can find a good one feel free. Just mention me in this issue if you do. 

Closing for now as this is complete.
