### ISSUE TITLE
🐞 Bug: panic: ENCRYPTION_KEY must be 32 bytes (raw/base64/hex). Provided=31 chars

### ISSUE THREAD

**Issue by priyajit4u** [ofkm/arcane#778]
### Bug Description

I am trying to use arcane via docker compose in my ubuntu linux vm.. weird problem that is arising is in docker logs it is saying : panic: ENCRYPTION_KEY must be 32 bytes (raw/base64/hex). Provided=31 chars although I have created both JWT and encryption key using : openssl rand -hex 32

### Steps To Reproduce

create a arcane docker compose
start via docker compose
in logs it says:
INF Arcane is starting
Oct 26 11:45:58.532 INF Database schema is up to date
Oct 26 11:45:58.532 INF Database initialized successfully
panic: ENCRYPTION_KEY must be 32 bytes (raw/base64/hex). Provided=31 chars

goroutine 1 [running]:
github.com/ofkm/arcane-backend/internal/utils.InitEncryption(0xc0006687e0)
	github.com/ofkm/arcane-backend/internal/utils/encryption.go:26 +0x456
github.com/ofkm/arcane-backend/internal/bootstrap.Bootstrap({0x41d3b20, 0x5fc9840})
	github.com/ofkm/arcane-backend/internal/bootstrap/bootstrap.go:54 +0x3f3
main.main()
	./main.go:12 +0x25

### Expected Behavior

i expected to open arcane webui 

### Actual Behavior

create a arcane docker compose
start via docker compose
in logs it says:
INF Arcane is starting
Oct 26 11:45:58.532 INF Database schema is up to date
Oct 26 11:45:58.532 INF Database initialized successfully
panic: ENCRYPTION_KEY must be 32 bytes (raw/base64/hex). Provided=31 chars

goroutine 1 [running]:
github.com/ofkm/arcane-backend/internal/utils.InitEncryption(0xc0006687e0)
	github.com/ofkm/arcane-backend/internal/utils/encryption.go:26 +0x456
github.com/ofkm/arcane-backend/internal/bootstrap.Bootstrap({0x41d3b20, 0x5fc9840})
	github.com/ofkm/arcane-backend/internal/bootstrap/bootstrap.go:54 +0x3f3
main.main()
	./main.go:12 +0x25

### Arcane Version

latest

### Operating System

Linux

### Browser

firefox

### Docker Version

24

**Comment by kmendell** [comment]
This is a very weird issue i thought i fixed it before but i must not of ill get it fixed.

**Comment by kmendell** [comment]
This should be fixed here: https://github.com/ofkm/arcane/commit/b3c7cb5bd64c6a5d49a0950ae7bde01f42910f4d.

Sorry about the trouble....

**Comment by robinsving** [comment]
This is still an issue for me when upgrading to 1.7.0
`openssl rand -base64 32`
