### ISSUE TITLE
🐞 Bug: Volume status Unused but it is in use

### ISSUE THREAD

**Issue by saitoh183** [ofkm/arcane#912]
### Bug Description

Docker Volumes using bind mount show up as Unused even when they are in use

### Steps To Reproduce

```
volumes:
  data_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/dockerconfig/arcane
  docker_volumes:
      external: true  
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    networks:
      saitohnet:
        ipv4_address: 172.20.0.14
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data_config:/app/data
      - /data/scripts/compose:/app/data/projects
    environment:
      APP_URL: ${APP_URL}
      PUID: ${PUID}
      PGID: ${PGID}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
networks:
  saitohnet:
    name: saitohnet
    external: true
```

### Expected Behavior

Status to be Green as Used

### Actual Behavior

Status is Unused

### Screenshots

<img width="1396" height="894" alt="Image" src="https://github.com/user-attachments/assets/fa3a9ac0-db34-4f22-83e3-5a6a82b78262" />

<img width="1617" height="622" alt="Image" src="https://github.com/user-attachments/assets/f8c3a433-9d64-4fa9-9871-731a803dff4b" />

### Arcane Version

v1.7.0

### Operating System

Linux

### Browser

Edge

### Docker Version

27.3.1 (API: 1.47)

### Additional Context

since the mountpoint /var/lib/docker/volumes/arcane_data_config/_data is actually pointer towards /data/docker-config/arcane and not the actual destination, i assume being a pointer is the issue.

**Comment by saitoh183** [comment]
updated to v1.7.2 and still have the same issue

**Comment by vladaurosh** [comment]
Why not update to the latest 1.8.1?

**Comment by saitoh183** [comment]
> Why not update to the latest 1.8.1?

I did a pull in arcane and that is the version it pulled. Im using latest tag so I assumed that was the latest

**Comment by saitoh183** [comment]
> Why not update to the latest 1.8.1?

I just noticed on the home page the repo change noticed. I checked the docker compose example and saw that it is now ghcr.io/getaracneapp/arcane:latest instead of ghcr.io/ofkm/arcane:latest. However when i use the new one i get this 

<img width="807" height="63" alt="Image" src="https://github.com/user-attachments/assets/f2cf6634-706b-42af-acc9-ee4164d0ea53" />

**Comment by vladaurosh** [comment]
Should be getarcaneapp not getaracneapp.

**Comment by saitoh183** [comment]
> Should be getarcaneapp not getaracneapp.

lol...i just saw that ...it will need to be corrected in the examples folder. But even with the v1.8.1 the issue is still there

<img width="1729" height="938" alt="Image" src="https://github.com/user-attachments/assets/41b49da5-fb03-45e9-8853-3b99b6c0a7db" />

**Comment by kmendell** [comment]
Try the `ghcr.io/getarcaneapp/arcane:next` image please, i cant reproduce this, but not saying its not an issue. I just cant remember if i fixed it or not in the latest code.

**Comment by saitoh183** [comment]
nope still an issue

<img width="1729" height="938" alt="Image" src="https://github.com/user-attachments/assets/4d2ca748-bb67-4404-a64e-ae760d5db41d" />

Also using the next tag must of migrated the DB in postgres cuz now i cant return to the latest tag, i get a migration error when the container starts

**Comment by kmendell** [comment]
@saitoh183 Yeah it does have a DB Migration my bad... You can stay on next for now nothing gets pushed to main without being stable so once i reelase the next version then you can switch back off of that the next tag. 

Ill hopefully get this fixed here in a bit

**Comment by saitoh183** [comment]
> [@saitoh183](https://github.com/saitoh183) Yeah it does have a DB Migration my bad... You can stay on next for now nothing gets pushed to main without being stable so once i reelase the next version then you can switch back off of that the next tag.
> 
> Ill hopefully get this fixed here in a bit

Np.. Im loving this program so far :)

**Comment by kmendell** [comment]
I think this should be fixed here: https://github.com/getarcaneapp/arcane/commit/71623e33eadf0111beadb241a2cac8f36ab28739. The next image should be updated shortly for you to test.

**Comment by saitoh183** [comment]
> I think this should be fixed here: [71623e3](https://github.com/getarcaneapp/arcane/commit/71623e33eadf0111beadb241a2cac8f36ab28739). The next image should be updated shortly for you to test.

ok using the same tag or do i need to switch back to latest?

**Comment by kmendell** [comment]
@saitoh183 Using the same `:next` image correct

**Comment by saitoh183** [comment]
Sweet it is working! Thanks!

<img width="1745" height="974" alt="Image" src="https://github.com/user-attachments/assets/d5eb371a-5ff7-4b91-a182-62099793c40b" />

**Comment by kmendell** [comment]
Awesome, this will be in the next release.
