### ISSUE TITLE
🐞 Bug: Incomplete data on dashboard view when switching between Arcane environments

### ISSUE THREAD

**Issue by Profex** [ofkm/arcane#961]
### Bug Description

When switching between Arcane environments the Containers and Images view is not properly refreshed, leading to incomplete data

### Steps To Reproduce

**Step 1 - connect to Arcane environment A with a large number of containers and images**

- Dashboard will list 9 recent containers, and 9 largest images
- For each the containers view and images view there is a text at the bottom stating "Showing 9 of XX containers" / "Showing 9 of YY images"

**Step 2 - Connect to Arcane environment B (via Arcane environment selector) with a small number of containers and images (5 of each in my case)**

- Dashboard will list 5 recent containers, and 5 largest images 
- There is no further text at the bottom since the containers / images do not exceed 9 on that environment

**Step 3 - connect again to Arcane environment A (via Arcane environment selector) - this is when the issue occurs**
Although the environment has a large number of containers & images (and they were displayed when accessing environment A the first time in step 1) only 5 of each are displayed (which is the number of containers & images of the previous view for step 2 /environment B), and there is no text at the bottom highlighting that there are more containers / images on environment A.
Complete data for environment A is only displayed if you do perform a full refresh in browser. Just hitting the "refresh" button at the top right corner in Arcane will not change anything.

### Expected Behavior

When switching between Arcane environments via Arcane environment selector the dashboard show always show the correct number of containers & images for the respective environemnt, without having to perform a page refresh in Browser

### Actual Behavior

Incomplete data is shown if you switch between environments as described above

### Screenshots

Can provide if required

### Arcane Version

v1.9.0

### Operating System

Other

### Browser

I tested Edge and Firefox, behaviour is the same in both

### Docker Version

24.0.2 (newest available version of Docker in Synology DSM)

**Comment by kmendell** [comment]
Should be fixed here: https://github.com/getarcaneapp/arcane/commit/f0be4d2ccabdc71c8550db0d119421fcaf57be0a, Thank you!

**Comment by Profex** [comment]
I tested via :next docker image and I can confirm that the issue is solved. Thank YOU for swift response and fix, and for creating and maintaining this really great docker management solution, perfectly fitting my needs!

**Update:**
After testing a bit more in detail I discovered one more glitch, which did not exist before. When accessing my environment A with more than 9 containers and more than 9 images the dashboard first shows 9 containers and 9 images along with text "Showing 9 of XX containers" and "Showing 9 of XX containers", but after less than a second the page updates automatically without user action and then only displays 8 containers and 8 images along with text "Showing 8 of XX containers" and "Showing 8 of XX containers".

**Update 2:**
What I described in my update only happens in Edge 142. In Chrome 142 and Firefox 144.0.1 always 8 containers / 8 images are shown right from the start when accessing the dashboard..

**Comment by Profex** [comment]
@kmendell what I described above in my update comments is still happening on v1.10.1 release. Should I open a new issues for this?
